title : Blog Title
tagline: Blog Tagline
author :
  name : Kai Curry
  email : blah@kaicurry.com
  github : webmasterkai
  twitter : kaicurry
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  - tips.md
  - tandf/index.md
